---

- name: Install requirements
  hosts: all
  become: true
  become_user: root
  gather_facts: false
  vars_files:
    - group_vars/vault.yml  
    
  tasks:
  - name: Install System Dependencies
    apt:
      name:
        - unzip
        - python3-ldap
        - ldap-utils
      state: present
      update_cache: yes
      

 